packages:
  - internal/*
  - 'apps/*'
  - 'packages/*'
  - scripts/*
catalog:
  '@eslint/js': ^9.24.0
  '@iconify/json': ^2.2.314
  '@iconify/tailwind': ^1.2.0
  '@next/eslint-plugin-next': ^15.3.1
  '@manypkg/get-packages': ^2.2.2
  '@tailwindcss/typography': ^0.5.16
  '@types/node': ^22.14.0
  '@types/react': ^19.1.0
  '@types/react-dom': ^19.1.1
  '@typescript-eslint/parser': ^8.30.1
  '@typescript-eslint/eslint-plugin': ^8.30.1
  autoprefixer: ^10.4.20
  cac: ^6.7.14
  chalk: ^5.4.1
  consola: ^3.4.0
  circular-dependency-scanner: ^2.3.0
  depcheck: ^1.4.7
  execa: ^9.5.2
  eslint: ^9.24.0
  eslint-config-prettier: ^10.1.1
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.4
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.19
  eslint-plugin-unused-imports: ^4.1.4
  eslint-plugin-import-x: ^4.10.5
  eslint-plugin-turbo: ^2.5.0
  globals: ^16.0.0
  postcss: ^8.5.3
  publint: ^0.2.12
  prettier: ^3.5.3
  prettier-plugin-tailwindcss: ^0.6.11
  react: ^19.0.0
  react-dom: ^19.0.0
  tailwind-merge: ^2.6.0
  tailwindcss: ^4.1.4
  tailwindcss-animate: ^1.0.7
  turbo: ^2.5.0
  typescript: ^5.8.2
  typescript-eslint: ^8.29.0
  vite: ^6.3.1
  unbuild: ^3.5.0
